### ISSUE TITLE
Favicon and website title

### ISSUE THREAD

**Issue by Kuboczoch** [alucard87pl/reactgate#7]
**What to add?**
A favicon and change website title to e.g. ReactGate

**Why should we add it?**
Professionalism.

**Additional context**
![image](https://user-images.githubusercontent.com/20823919/61800072-a154e400-ae2c-11e9-90d3-cd44c7d3ec50.png)

**Comment by alucard87pl** [comment]
Fixed in 104be996fcb96b09083c89bae0623b993bc681c2
